packages:
  - paru
  - microsoft-edge-stable-bin
  - xdg-desktop-portal
  - xdg-desktop-portal-gtk
  - xdg-desktop-portal-gnome
  - xdg-utils
  - vi
  - vim
  - neovim
  
files:
  - source: ${config_root}/files/config/microsoft-edge-stable-flags.conf
    target: ~/.config/microsoft-edge-stable-flags.conf
    symlink: true

exports:
  - microsoft-edge-stable