packages:
  - zoxide
  - fzf

scripts:
  - script: ${config_root}/scripts/aerial-sddm-theme.sh
    sudo: true
    depends:
      - packages: [git]
      - services: [sddm]
      - folders: ["!/usr/share/sddm/themes/aerial-sddm-theme"]
  
  - script: ${config_root}/scripts/configure-zoxide.sh
    depends:
      - packages: [zoxide, fzf]
      
commands:
  - name: Git Config
    command: |
      git config --global user.name "Raymond Bennett"
      git config --global user.email "raymond.bennett@gmail.com"
    depends:
      - packages: [git]
    rollback: |
      git config --global --unset user.name
      git config --global --unset user.email

secrets:
  ssh_id_ed25519: !encrypted x4Ymy7QRZy+muTonTD21H4vODMLPPGAZNg+IxlBU760tJD/Y03dmqKcFv2cInY7HpqgJcT4TqPm9u5wgGQFqJdH5Tk/1baJMaeVoVYl/c8sPeIlGLHt4k2V3ZiKOyOzFyJqNTxChLsd8F0wAxS9L3UMoyIRjPFfJG9kPeq23K/gN58j/jw6XDli3k3m0GgrCvDSDPo/9s9iPclOcQsr4/MSbOAWfjakkBIOwfiYXcQH4J5n/zLv5m9X9p0TZ9GLJaLtuKglRHNZj6tgOkQkpCZUIFBNdCZDWJt7OnqAE6c3DvoyjZud/ac/BDRT6VjliKxGNdC+yyoqc/OUwZqLS91/tt8SJvNEhPw3VIObX+BlatC9ztgaEqe/dpAYMLYts0Bqb0ec0X/JDgePSxHrWP+54F4fVd82Okcky/1qv/igrAgdve1gmw17iCol+WQJ7b3Ctmi9EsVC9mH/lg9U8narPCp0PdMp5zENq/3oWhOxcqy3j8gjZy6tw9k2kKfeUhh7Ieg8jEzVxqCkLPPCibxZqbOroCMMGrKzajdI8mgOIT9z1z8FFJeTHbUN0EgYNANYthVT1dZQIvwdSlfhOxMSqJ8oqrzIkuQmGEVzsTmhZdzjFGTpo2HDqNlukBI190b5Z5sKvAKiA79JEKzKD7/VfGkRdpWpxntVkiQ==

files:
  - source: ${secrets.ssh_id_ed25519}
    target: "~/.ssh/id_ed25519"
    mode: "0600"

  - source: ${config_root}/files/niri.screenshot.sh
    target: ~/.local/bin/niri-screenshot.sh
    symlink: true
    mode: "+x"
    
  - source: git@github.com:rayzorben/dotfiles.git
    target: ~/dotfiles
    ssh_key: ["~/.ssh/id_ed25519"]
    depends:
      - file: ["~/.ssh/id_ed25519"]

containers:
  - name: redis
    image: redis:alpine
    restart: unless-stopped
    network_mode: host
    volumes:
      - "${config_root}/data/redis:/data"
    depends:
      - services: [docker]

ghostty: !include "./commands/ghostty.yaml"

      
distrobox:
  - name: sedanos
    image: docker.io/cachyos/cachyos-v3:latest
    home: /home/distrobox/sedanos
    home_sudo: true
    exports:
      - microsoft-edge-stable
      - code
      - cursor
      - StorageExplorer

    packages:
      - paru
      - microsoft-edge-stable-bin
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-gnome
      - visual-studio-code-bin
      - cursor-bin
      - azure-cli
      - storageexplorer
      - jdk-openjdk
      - pulumi

    commands:
      - name: Install Databricks CLI
        command: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
        sudo: true
      - name: Install uv
        command: |
          curl -LsSf https://astral.sh/uv/install.sh | sh