user_config: !include "${config_root}/users/${env:USER}.yaml"
host_config: !include "${config_root}/hosts/$(hostname).yaml"

variables:
  dropbox_folder: ~/Dropbox
  lucida_font: ${config_root}/files/fonts/LucidaProgrammerNerdFontMono-Regular.ttf
  ttf_fonts: /usr/share/fonts/TTF

packages:
  - neovim
  - git
  - docker
  - dropbox
  - dsearch-bin
  
groups:
  - wheel
  - docker

users:
  - username: rayben
    name: Ray Bennett
    shell: /bin/fish
    groups: ['wheel', 'docker']

services:
  - service: docker
    depends:
      - packages: ['docker']
  - service: dsearch
    user: true
    depends:
      - packages: ['dsearch-bin']

files:
  - source: ${lucida_font}
    target: ${ttf_fonts}
    sudo: true

secrets:
  _verify: !encrypted sn+HxIuQgQPiWUqaJZkumrQQWr+18XTZyAd6+9kYPLKj/ETTZ2X/RGw5CtUBPuFz4bBQqY8hTC7CJlWfzj8=
